### ISSUE TITLE
OpenNebula 5.8.1+ changed VirtualMachinePool API making info! protected

### ISSUE THREAD

**Issue by cphoward** [fog/fog-opennebula#1]
OpenNebula modified their VirtualMachinePool API by changing calls from `info!` to `info` (RubyDocs indicate this is true for 5.8.1 through 5.8.5). The `info!` method seems to have been made protected in the process. The following files appear to be affected by this change:

- lib/fog/opennebula/requests/compute/vm_resume.rb
- lib/fog/opennebula/requests/compute/vm_shutdown.rb
- lib/fog/opennebula/requests/compute/vm_stop.rb
- lib/fog/opennebula/requests/compute/vm_destroy.rb
- lib/fog/opennebula/requests/compute/vm_suspend.rb
- lib/fog/opennebula/requests/compute/list_vms.rb
- lib/fog/opennebula/requests/compute/vm_disk_snapshot.rb

I am not entirely certain why this change was made to OpenNebula, but it appears to have been a recent introduction.

**Comment by dann1** [comment]
thanks !!!

**Comment by dann1** [comment]
Fixed by https://github.com/fog/fog-opennebula/commit/ad2ad75dab1b7e5d234c86f6e0962ac7e51e54c9
