### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by damacus** [fog/fog-opennebula#10]
Hello! 

I'm trying to use this Gem with kitchen-opennebula but it looks like the release and tags don't match what's on RubyGems. 

Is there any chance we can get a release of this? If you need a GitHub Action for releasing it, this one has worked well for me: https://github.com/test-kitchen/kitchen-vro/blob/main/.github/workflows/publish.yaml

**Comment by dann1** [comment]
Thanks for pointing this out. I pushed the tags and made the release manually. Since we don't update this too often we haven't really automated the release process. Will keep this issue open and when the next update happens we will make sure the github actions is implemented.

Renaming the title.

**Comment by dann1** [comment]
https://github.com/fog/fog-opennebula/actions
