### ISSUE TITLE
Adding fog-opennebula to rubygems.org

### ISSUE THREAD

**Issue by cphoward** [fog/fog-opennebula#4]
@dann1, 

Would you be willing to add this gem to https://rubygems.org/?

**Comment by dann1** [comment]
Yes. It would be nice to have this option, it will be uploaded there.

**Comment by cphoward** [comment]
@dann1,

I'm willing to help get it uploaded if you'd like. Just let me know.

**Comment by cphoward** [comment]
@dann1,

I have added the gem to ruby gems. Let me know which user to add so you have ownership.

https://rubygems.org/gems/fog-opennebula

**Comment by dann1** [comment]
Hello, thanks for the upload, you can add [this user](https://rubygems.org/profiles/dann1)

**Comment by cphoward** [comment]
You have been added to the gem.
